### ISSUE TITLE
WebSocket connection failed

### ISSUE THREAD

**Issue by Yasso9** [pi0/nuxt-websocket#2]
On the website https://nuxt-websocket.pages.dev/ or when doing 

```
git clone https://github.com/pi0/nuxt-websocket.git
npm install
npm run dev
```

I have the same error log

```
[ws] ws Connecting to wss://nuxt-websocket.pages.dev/_ws ...
entry.DSmqJoAi.js:17 WebSocket connection to 'wss://nuxt-websocket.pages.dev/_ws' failed: 
```

**Comment by pi0** [comment]
Intresting... maybe you are behind a proxy?

<img width="790" alt="image" src="https://github.com/pi0/nuxt-websocket/assets/5158436/5be3335a-5f05-46bf-9d50-daffcaf35186">

**Comment by Yasso9** [comment]
Thank you for you answer. You were right it was my enterprise proxy causing that. I did disable the SOCKS Host proxy and now it work on the browser for https://nuxt-websocket.pages.dev/

However I still didn't manage to make the local installation working even if I disabled ethernet and removing env variable proxy (`$http_proxy, $https_proxy, $ftp_proxy, $no_proxy`)

**Comment by JCtapuk** [comment]
> Thank you for you answer. You were right it was my enterprise proxy causing that. I did disable the SOCKS Host proxy and now it work on the browser for https://nuxt-websocket.pages.dev/
> 
> However I still didn't manage to make the local installation working even if I disabled ethernet and removing env variable proxy (`$http_proxy, $https_proxy, $ftp_proxy, $no_proxy`)

Chances are it's the node adapter that's to blame

**Comment by JCtapuk** [comment]
nitro-dev is created here
```ts
const server = new Server(toNodeListener(nitroApp.h3App));

if (import.meta._websocket) {
  const { handleUpgrade } = wsAdapter(nitroApp.h3App.websocket);
  server.on("upgrade", handleUpgrade);
}
```
And at the adapter
```ts
export default defineWebSocketAdapter<NodeAdapter, NodeOptions>(
  (options = {}) => {
    const crossws = createCrossWS(options);

    const wss: WebSocketServer =
      options.wss ||
      (new _WebSocketServer({
        noServer: true,
        ...(options.serverOptions as any),
      }) as WebSocketServer);
```
As a result, the websocket on which port is not called will ultimately not connect to it

**Comment by pi0** [comment]
@JCtapuk Not sure to follow. When you use `pnpm dev` it does fail to work in your local env?

**Comment by JCtapuk** [comment]
> @JCtapuk Not sure to follow. When you use `pnpm dev` it does fail to work in your local env?

No I use npm or yarn. The client just connects for a long time without an upgrade approval response.

**Comment by JCtapuk** [comment]
![image](https://github.com/pi0/nuxt-websocket/assets/61321608/40d597c0-93cc-42e3-90ec-932882afd2ae)

**Comment by pi0** [comment]
That's very strange. I wonder if it might be Windows specific. Have you tried on SQL by any chance?

**Comment by JCtapuk** [comment]
> That's very strange. I wonder if it might be Windows specific. Have you tried on WSL by any chance?

![image](https://github.com/pi0/nuxt-websocket/assets/61321608/39bb639f-1aa8-4d3b-9e6e-df481bbaacec)
No, I'm using pure ubuntu

**Comment by JCtapuk** [comment]
> That's very strange. I wonder if it might be Windows specific. Have you tried on WSL by any chance?

And if you run it from an example or in a sandbox https://stackblitz.com/github/unjs/crossws/tree/main/examples/h3?file=index.ts
That's normal. Apparently something locally doesn’t want to connect. And if I run a pure websocket server it works great

**Comment by JCtapuk** [comment]
![image](https://github.com/pi0/nuxt-websocket/assets/61321608/b628cab9-2fa3-4d94-aa87-88f154874ca9)
I launched it purely without nitro, that is, crossws works. But when it is connected to nitro, the adapter apparently stopped working

**Comment by JCtapuk** [comment]
@pi0 And it seems he earned it. Restarted the project and now it works fine. It's not clear what happened before

**Comment by pi0** [comment]
Okay cool. I will be closing this issue then but if you continued to experience similar issues, feel free to open another to investigate better.
